server:
  port: 8090

config:
  base:
    endpoint:
      customer: http://localhost:8081/customer

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/ProyectoS1Bank 
      auto-index-creation: true
  application:
    name: credit-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
