server:
  port: 8081
  error:
    include-stacktrace: always

spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb+srv://bootcamp:Bootc4mp@cluster0.qqzxn.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-bank.azurewebsites.net/eureka

resilience4j:
    circuitbreaker:
        configs:
            default:
                registerHealthIndicator: true
                slidingWindowSize: 10
                minimumNumberOfCalls: 5
                permittedNumberOfCallsInHalfOpenState: 3
                automaticTransitionFromOpenToHalfOpenEnabled: true
                waitDurationInOpenState: 2s
                failureRateThreshold: 50
                eventConsumerBufferSize: 10
                recordExceptions:
                    - org.springframework.web.client.HttpServerErrorException
                    - java.util.concurrent.TimeoutException
                    - java.io.IOException
                    - java.net.ConnectException
        instances:
            customerServiceCircuitBreaker:
                baseConfig: default
  

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
      root: DEBUG


