server:
  port: 8098

spring:
  data:
    mongodb:
      uri: mongodb://mongo-server:27017/ProyectoS1Bank
  application:
    name: debitcard-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka