server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://mongo-server:27017/ProyectoS1Bank
      auto-index-creation: true
  application:
    name: fixedTermAccount-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/