server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/ProyectoS1Bank
      auto-index-creation: true
  application:
    name: fixedTermAccount-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/