server:
  port: 8071

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/ProyectoS1Bank
  application:
    name: publish-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

tipo:
  cambio:
    venta: 7.0
    compra: 6.5
