server:
  port: 8070

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/ProyectoS1Bank
  application:
    name: transfercoin-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
