server:
  port: 8075

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/ProyectoS1Bank
      auto-index-creation: true
  application:
    name: yanki-deposit-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka